name: hello-world
on: push
jobs:
  hellow-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
